title: Cosicas de Steam
tagline: "Porque hay mucho donde escoger"
url: "https://throyd.github.io/steamstuff" # The base hostname & protocol for your site. Use it if you need absolute URL's


collections:
  games:
    name:
    steamid:
    developer: 
    publisher:
    launchdate: 
    output: true
    permalink: /juegos/:title/
  reviews:
    name:
    gamename:
    version:
    author:
    publisheddate:
    thumbs:
    output: true
    permalink: /criticas/:title/

defaults:
  -
    scope:
      path: ""
      type: "games"
    values:
      layout: "game"
  -
    scope:
      path: ""
      type: "reviews"
    values:
      layout: "review" 
      author: "Jhin"
    
